
dist: trusty
sudo: false

language: php

php:
  - 7.1
  - 7.2
  - 7.3

install:
  - composer self-update
  - composer --prefer-dist install

script:
  - ./vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 src/ tests/Test
  - 'if [ {$TRAVIS_PHP_VERSION} = "7.3" ]; then
      ./vendor/bin/phpunit --process-isolation -v --debug --coverage-clover=coverage.clover;
    else
      ./vendor/bin/phpunit -v --debug --no-coverage;
    fi'

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.3" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.3" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
